name: Clean archive

on:
  push:
    branches: [ master ]
  workflow_dispatch:

concurrency: 
  group: "clean"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run script
      run: |
        python3 .github/clean.py
    
    - name: Push archive
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add .
        git commit --amend -m "Build $GITHUB_SHA" || exit 0   # do not error if nothing to commit
        git push --force